### ISSUE TITLE
Problem with template argument

### ISSUE THREAD

**Issue by Melab** [zerovm/toolchain#23]
Excerpt of make output:

     ../../../SRC/.gcc-extra-ppl/src/Grid_Generator_System.defs.hh:272:28: error: template argument 3 is invalid
        const Grid_Generator&>,
                             ^
    
    Makefile:1159: recipe for target 'Scalar_Products.lo' failed

**Comment by pkit** [comment]
Distro? Distro version? gcc version? make version?

**Comment by Melab** [comment]
Ubuntu 14.10 running kernel version 3.16.0-30-generic
GNU Make 4.0
Ubuntu's branch of GCC 4.9.1

**Comment by pkit** [comment]
Hmm, out of that bunch I think we never tested with gcc 4.9.x
Are these all standard Ubunru 14.10 packages?
I will install and test if they are.

**Comment by rampage644** [comment]
I have no luck with building toolchain on Arch with gcc4.9+

**Comment by pkit** [comment]
Good to know, so it's probably incompatibility with 4.9.x, because it's fine in any 4.8.x

**Comment by pkit** [comment]
Ok, looks like this bug/workaround to me: https://sourceware.org/ml/crossgcc/2014-05/msg00032.html

**Comment by pkit** [comment]
Build here under Ubuntu 14.10 after https://github.com/zerovm/glibc/commit/a29f42dc30c13bc866ec4c6b67b163b3235c326c and https://github.com/zerovm/toolchain/commit/69ae452fb84bb429dab7a11ca5baee98ec706623 are applied.

**Comment by Melab** [comment]
Thank you!
